### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by vladholubiev** [vladgolubev/simple-ecs-restart-cli#1]
- [ ] Search as you type for services list❗️ 
- [ ] Allow to select multiple services
- [ ] Remember last selected cluster and region
- [x] Load list of clusters
